config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'welcome/index'
  mount API::Base => '/api'

  devise_for :users

  root 'welcome#index'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<h1 class="text-center">Emily's Secret</h1>
<div class="text-center">
  <%= image_tag("launcher.png")%>
</div>




<div class="container">
  <div class="featurette">

    <h3>Is your sex life perfect?</h3>

    <p>After every sexual encounter do you lie back thinking OMG, that was frigging awesome! Is life behind the bedroom door one long, non-stop raunchy adventure? Do you feel overwhelmingly satisfied</p>

    <p>Yes? then this app is NOT for you.</p>

    <p>If, on the other hand, you are like me, you know there is room for improvement between the sheets, this app could be just what you and your partner have been waiting for.</p>

    SPECIAL NOTE: To play Emily’s Secret game, both you AND your partner need to download a copy of the app on your phones or tablet.

    Whether you are long-time couple or just starting a new relationship, this interactive app has everything you need for a complete evening of unforgettable erotic adventure.

    This app guarantees awesome sex. It will remind you what a hot couple you are.



    <h4>WHAT CAN YOU EXPECT FROM THE GAME?</h4>

    It will teach you some wild new techniques and give you the courage to start using them right now. This app is going to walk you and your partner right up to the edge of your boundaries … and dare you to jump over … always with a great big smile on your faces.

    That’s because you don’t just simply read the screens, you get to bring these hot adventures to life. Everything you need is in the app:

    -	Cool tricks and surprises for teasing your partner
    -	How to make your mate feel sexy
    -	How to initiate new adventurous activities
    -	Ways to learn about your partners unspoken desires
    -	Improve your techniques with lots of secret sex tips

    Each game is complete evening of seduction, from a flirty beginning to a very happy ending. You are led by the hand every step of the way. Just follow along and learn by doing.

    The app is about more than just getting down and dirty. Before you even get naked, each game starts with fun questions carefully worded to avoid embarrassment, but open enough to allow your partner to reveal what they really enjoy. You will probably be amazed … and delighted …. by what you discover.



    <h4>HOW IT WORKS</h4>

    You and your partner download the app on both your phones or tablets.

    Link together via Wi-Fi and you are ready to play.

    Games start with fun, intimate questions and slowly builds to more erotic and adventurous activities.

    I don’t want to tell you more as it will spoil the surprise and fun. Anticipation is the best aphrodisiac!

    Download it now and prepare yourself for some mind-blowing, toe-curling nights of steamy passion.
      <p class="text-center"><%= link_to image_tag("apple.png", size: "120x50", alt: "iOS Store"), "#", target:"_blank" %>
      <%= link_to image_tag("google.png", size: "120x50", alt: "Android play Store"), "#" , target:"_blank" %></p>
  </div>
</div>

<div class="footer">
  <p class="text-center"><%= link_to "Admin", new_admin_user_session_path %></p>
</div>